nameOverride: finance-svc

image:
  repository: erp/finance-svc

service:
  port: 3001
  grpcPort: 50051

database:
  host: postgresql.erp-infra.svc.cluster.local
  port: 5432
  name: finance_db

kafka:
  groupId: finance-svc
