"use client";

import React from "react";
import {
  Activity,
  ArrowLeftRight,
  ArrowRightLeft,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  CalendarDays,
  CalendarOff,
  CheckSquare,
  ChevronDown,
  ChevronRight,
  ClipboardList,
  Clock,
  CreditCard,
  DollarSign,
  Factory,
  FileText,
  FileX,
  Files,
  FolderKanban,
  FolderOpen,
  GitBranch,
  GitPullRequest,
  GraduationCap,
  Globe,
  HelpCircle,
  Home,
  Key,
  LayoutDashboard,
  Layers,
  Link,
  List,
  LogOut,
  Menu,
  Package,
  PackageCheck,
  PiggyBank,
  Plug,
  PlugZap,
  Receipt,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Timer,
  TrendingUp,
  Truck,
  Upload,
  User,
  UserCircle,
  Users,
  Warehouse,
  X,
} from "lucide-react";

/**
 * Centralized icon registry mapping string names (from module config)
 * to actual lucide-react icon components.
 */
export const iconMap: Record<string, React.ElementType> = {
  Activity,
  ArrowLeftRight,
  ArrowRightLeft,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  CalendarDays,
  CalendarOff,
  CheckSquare,
  ChevronDown,
  ChevronRight,
  ClipboardList,
  Clock,
  CreditCard,
  DollarSign,
  Factory,
  FileText,
  FileX,
  Files,
  FolderKanban,
  FolderOpen,
  GitBranch,
  GitPullRequest,
  Globe,
  GraduationCap,
  HelpCircle,
  Home,
  Key,
  LayoutDashboard,
  Layers,
  Link,
  List,
  LogOut,
  Menu,
  Package,
  PackageCheck,
  PiggyBank,
  Plug,
  PlugZap,
  Receipt,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Timer,
  TrendingUp,
  Truck,
  Upload,
  User,
  UserCircle,
  Users,
  Warehouse,
  X,
  // Lowercase aliases for backward compatibility with core portal menu
  home: Home,
  users: Users,
  building: Building2,
  "user-circle": UserCircle,
  globe: Globe,
  settings: Settings,
  shield: Shield,
};

/**
 * Resolve an icon by name, returning a rendered React element.
 * Falls back to LayoutDashboard if not found.
 */
export function getIcon(name: string, className = "w-5 h-5"): React.ReactElement {
  const Icon = iconMap[name] || LayoutDashboard;
  return <Icon className={className} />;
}
