export enum WorkflowStepType {
  SINGLE_APPROVER = 'SINGLE_APPROVER',
  ALL_APPROVERS = 'ALL_APPROVERS',
  ANY_APPROVER = 'ANY_APPROVER',
  AUTO_APPROVE = 'AUTO_APPROVE',
  MANAGER_CHAIN = 'MANAGER_CHAIN',
}
