apiVersion: v1
kind: Namespace
metadata:
  name: erp-core
  labels:
    app.kubernetes.io/part-of: erp
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: erp-platform
  labels:
    app.kubernetes.io/part-of: erp
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: erp-infra
  labels:
    app.kubernetes.io/part-of: erp
---
apiVersion: v1
kind: Namespace
metadata:
  name: erp-observability
  labels:
    app.kubernetes.io/part-of: erp
---
apiVersion: v1
kind: Namespace
metadata:
  name: erp-gateway
  labels:
    app.kubernetes.io/part-of: erp
    istio-injection: enabled
